### ISSUE TITLE
Translate models from MongoDB to InfluxDB

### ISSUE THREAD

**Issue by isaacvr** [isaacvr/lacetel_server#1]
**Is your feature request related to a problem? Please describe.**
The models for the database needs to be translated from MongoDB to InfluxDB.

**Describe the solution you'd like**
Translation must  affect models:
- [x] `region`
- [x] `sensor`
- [x] `service`
- [x] `transmitter`

**Describe alternatives you've considered**
Use the `user` model as a reference.

**Comment by arielcv** [comment]
I'll work with transmitter

**Comment by isaacvr** [comment]
Closed with [5c156fb](https://github.com/isaacvr/lacetel_server/commit/5c156fb2f90ca7d7b0af0144564dd5536fec3b13)
